name: observability-workflow
on: [push]
jobs:
  application:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: setup jdk 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'
    - run: chmod +x gradlew
    - run: ./gradlew build --no-daemon