name: workflow-build-api-observability
on: [push]
jobs:
  application:
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v4
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'
    - run: chmod +x gradlew
    - run: ./gradlew build --no-daemon