name: workflow-api-observability
on: 
  pull_request:
    branches:
      - develop
jobs:
  application:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'
    - run: chmod +x gradlew
    - run: ./gradlew build --no-daemon